list_of_numbers = [1, 2, 3, 4, 54, 65, 7676, 754745]
list_of_numbers.append(4)
print(list_of_numbers)
list_of_numbers.pop(2)
print(list_of_numbers)
list_of_numbers.extend([1, 3, 4])
print(list_of_numbers)
print(list_of_numbers.index(4))
list_of_numbers.insert(0, 5)
print(list_of_numbers)
list_of_numbers.remove(1)
print(list_of_numbers)
print(list_of_numbers.count(4))
list_of_numbers.sort()
print(list_of_numbers)
list_of_numbers.reverse()
print(list_of_numbers)
new_list = list_of_numbers.copy()
print(new_list)
new_list.clear()
print(new_list, list_of_numbers)
